name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - docker-compose.yml
      - .github/workflows/publish.yaml
      - fun.sh
      - lipsum.txt
      - Dockerfile
  workflow_dispatch:

permissions:
  packages: write

jobs:
  publish:
    name: Publish image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/386
            linux/amd64
            linux/arm
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
          tags: |
            favware/cgi-linux-training:latest
            ghcr.io/favna/linux-workshop:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: favware/cgi-linux-training
            enable-url-completion: true
            short-description: CGI Linux Training Workshop
